dist: trusty

language: perl
perl:
 - "5.10"
 - "5.12"
 - "5.14"
 - "5.16"
 - "5.18"
 - "5.20"
 - "5.22"
 - "5.24"
 - "5.26"
 - "5.28"

install:
  - dzil authordeps --missing | cpanm --notest --no-skip-satisfied
  - PERL_MM_USE_DEFAULT=1 dzil listdeps --author --missing | cpanm --notest --no-skip-satisfied

script:
  - PERL_MM_USE_DEFAULT=1 dzil test --author --release
